#define GT_TOSHIN2 "“¬_“ss‡U@‚†‚‚’@‚v‚‰‚‚X‚T@"
#define GT_RANCE4 "‚q‚‚‚ƒ‚…‚S@|‹³’c‚ÌˆâY|@‚e‚‚’@‚v‚‰‚‚X‚T@"
#define GT_RANCE5D "ƒ‰ƒ“ƒX‚T‚c@iSRj"
#define GT_ESUKA "-BeatAngelEscalayer-"
#define GT_RANCE3_ENG "Rance3"
#define GT_RANCE4_ENG "Rance4 -Legacy of the Sect- For Win95 "
