name: Android Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Deps
      run: sudo apt install ninja-build

    - name: Build
      run: |
        cd android
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > keystore.jks
        ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk-bundle ./gradlew assembleRelease
      env:
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: xsystem35-apk
        path: android/app/build/outputs/apk/release/app-release.apk
